# Site settings
title:          Lunatichub
description:    
baseurl:        "/lunatichub"
url:            "https://frospirum.github.io"

# Google Analytics
google_analytics: UA-220185736-1

# Author
author:
  name:         frospirum
  url:          https://frospirum.github.io
  email:        frospirum@outlook.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale